<a href="https://colab.research.google.com/github/sorotdaniel/portfolio-soro/blob/main/seance3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

# Fixer la graine pour la reproductibilité
np.random.seed(42)

def generate_messy_data(n=1000):
    data = {
        'ID_Client': range(1000, 1000 + n),
        'Age': np.random.choice([25, 35, 45, 150, np.nan, 18], size=n),
        'Revenu_Annuel': np.random.normal(50000, 15000, n),
        'Score_Credit': np.random.randint(300, 850, n),
        'Education': np.random.choice(['Lycée', 'Licence', 'Master', None], n),
        'Ville': np.random.choice(['Paris', 'Lyon', 'Marseille', 'Pris', 'Lyon '], n),
        'Taux_Endettement': np.random.choice(['0.3', '30%', '0.15', '15%', np.nan], n),
        'Date_Ouverture': [datetime(2010, 1, 1) + timedelta(days=np.random.randint(0, 4000)) for _ in range(n)],
        'Genre': np.random.choice(['M', 'F', 'Inconnu'], n),
        'Pret_Accorde': np.random.choice(['Oui', 'Non'], n)
    }

    df = pd.DataFrame(data)

    # Injecter des erreurs spécifiques
    df.loc[0:10, 'Score_Credit'] = -999  # Valeurs impossibles
    df.loc[20:30, 'Revenu_Annuel'] = df.loc[20:30, 'Revenu_Annuel'] / 1000 # Erreur d'unité

    return df

df = generate_messy_data()
df.to_csv('credit_risk_tp.csv', index=False)
print("Dataset 'credit_risk_tp.csv' généré avec succès !")

Dataset 'credit_risk_tp.csv' généré avec succès !

In [ ]:
df = pd.read_csv('/content/credit_risk_tp.csv')

In [ ]:
df

,ID_Client,Age,Revenu_Annuel,Score_Credit,Education,Ville,Taux_Endettement,Date_Ouverture,Genre,Pret_Accorde
0,1000,150.0,40240.361463,-999,NaN,Lyon,NaN,2013-12-16,Inconnu,Non
1,1001,NaN,42693.119244,-999,Licence,Lyon,0.3,2013-08-10,Inconnu,Non
2,1002,45.0,41114.091136,-999,Lycée,Lyon,0.15,2013-06-23,Inconnu,Oui
3,1003,NaN,37040.138455,-999,Licence,Marseille,30%,2020-04-30,M,Oui
4,1004,NaN,50727.824419,-999,Lycée,Paris,0.15,2014-04-29,M,Non
...,...,...,...,...,...,...,...,...,...,...
995,1995,18.0,58887.904238,681,Licence,Pris,30%,2010-12-04,F,Oui
996,1996,NaN,61675.416142,795,Master,Paris,15%,2015-12-11,F,Non
997,1997,25.0,41732.214255,678,Master,Marseille,0.3,2014-09-25,F,Non
998,1998,25.0,37727.016749,346,NaN,Pris,0.3,2011-03-23,M,Oui
999,1999,NaN,49949.383139,827,Lycée,Lyon,30%,2017-04-12,Inconnu,Non

In [ ]:
# 2. Nettoyage de la colonne 'Taux_Endettement' (Mélange de string et float)
def clean_debt_ratio(val):
    if pd.isna(val): return np.nan
    val = str(val).replace('%', '')
    val = float(val)
    return val / 100 if val > 1 else val

df['Taux_Endettement'] = df['Taux_Endettement'].apply(clean_debt_ratio)

In [ ]:
df

,ID_Client,Age,Revenu_Annuel,Score_Credit,Education,Ville,Taux_Endettement,Date_Ouverture,Genre,Pret_Accorde
0,1000,150.0,40240.361463,-999,NaN,Lyon,NaN,2013-12-16,Inconnu,Non
1,1001,NaN,42693.119244,-999,Licence,Lyon,0.30,2013-08-10,Inconnu,Non
2,1002,45.0,41114.091136,-999,Lycée,Lyon,0.15,2013-06-23,Inconnu,Oui
3,1003,NaN,37040.138455,-999,Licence,Marseille,0.30,2020-04-30,M,Oui
4,1004,NaN,50727.824419,-999,Lycée,Paris,0.15,2014-04-29,M,Non
...,...,...,...,...,...,...,...,...,...,...
995,1995,18.0,58887.904238,681,Licence,Pris,0.30,2010-12-04,F,Oui
996,1996,NaN,61675.416142,795,Master,Paris,0.15,2015-12-11,F,Non
997,1997,25.0,41732.214255,678,Master,Marseille,0.30,2014-09-25,F,Non
998,1998,25.0,37727.016749,346,NaN,Pris,0.30,2011-03-23,M,Oui
999,1999,NaN,49949.383139,827,Lycée,Lyon,0.30,2017-04-12,Inconnu,Non

In [ ]:
df.to_csv('credit_risk.csv', index=False)

In [ ]:
df

,ID_Client,Age,Revenu_Annuel,Score_Credit,Education,Ville,Taux_Endettement,Date_Ouverture,Genre,Pret_Accorde
0,1000,150.0,40240.361463,-999,NaN,Lyon,NaN,2013-12-16,Inconnu,Non
1,1001,NaN,42693.119244,-999,Licence,Lyon,0.30,2013-08-10,Inconnu,Non
2,1002,45.0,41114.091136,-999,Lycée,Lyon,0.15,2013-06-23,Inconnu,Oui
3,1003,NaN,37040.138455,-999,Licence,Marseille,0.30,2020-04-30,M,Oui
4,1004,NaN,50727.824419,-999,Lycée,Paris,0.15,2014-04-29,M,Non
...,...,...,...,...,...,...,...,...,...,...
995,1995,18.0,58887.904238,681,Licence,Pris,0.30,2010-12-04,F,Oui
996,1996,NaN,61675.416142,795,Master,Paris,0.15,2015-12-11,F,Non
997,1997,25.0,41732.214255,678,Master,Marseille,0.30,2014-09-25,F,Non
998,1998,25.0,37727.016749,346,NaN,Pris,0.30,2011-03-23,M,Oui
999,1999,NaN,49949.383139,827,Lycée,Lyon,0.30,2017-04-12,Inconnu,Non

# Étape 1: Correction des fautes

In [ ]:
# 3. Correction des fautes de frappe (Ville)
df['Ville'] = df['Ville'].str.strip().replace({'Pris': 'Paris'})

# Étape 2 : Gestion des Valeurs Manquantes (Imputation)

In [ ]:
# Imputation par la médiane pour l'Age (Ratio - robuste aux outliers)
df['Age'] = df['Age'].fillna(df['Age'].median())

# Imputation par le mode pour l'Education (Ordinal)
mode_edu = df['Education'].mode()[0]
df['Education'] = df['Education'].fillna(mode_edu)

# Suppression des lignes si le Genre est 'Inconnu' (Choix stratégique)
df = df[df['Genre'] != 'Inconnu']

In [ ]:
# Correction des scores de crédit négatifs (Intervalle)
df.loc[df['Score_Credit'] < 0, 'Score_Credit'] = df['Score_Credit'].median()

In [ ]:
# Plafonnement de l'âge (Ratio)
df.loc[df['Age'] > 100, 'Age'] = df['Age'].median()

In [ ]:
# Correction du revenu (si < 1000, on considère que c'est en K€ et on multiplie par 1000)
df.loc[df['Revenu_Annuel'] < 1000, 'Revenu_Annuel'] *= 1000

In [ ]:
df

# Étape 4 : Encodage des Variables Catégorielles

In [ ]:
# A. Encodage Ordinal (Education : il y a une hiérarchie)
edu_mapping = {'Lycée': 1, 'Licence': 2, 'Master': 3}
df['Education'] = df['Education'].map(edu_mapping)

In [ ]:
# B. Encodage Nominal / One-Hot (Ville : pas de hiérarchie)
df = pd.get_dummies(df, columns=['Ville', 'Genre'], drop_first=True)

In [ ]:
# C. Encodage de la Cible (Target)
df['Pret_Accorde'] = df['Pret_Accorde'].map({'Oui': 1, 'Non': 0})

In [ ]:
df

# création de variables(Ingenierie de caracteristiques)

In [ ]:
df['Date_Ouverture'] = pd.to_datetime(df['Date_Ouverture'])
reference_date = pd.to_datetime('2026-01-01')
df['Ancienneté_Jours'] = (reference_date - df['Date_Ouverture']).dt.days
df.drop('Date_Ouverture', axis=1, inplace=True)

In [ ]:
df